### ISSUE TITLE
预测代码是不是给错了？

### ISSUE THREAD

**Issue by AFunFun222** [GJCEXP/HetCoS#1]
你好，通过阅读你们的论文我感觉你们提出的HETCOS十分有趣，并想通过复现你们的成果来学习你们的思想，但我在排查代码的时候发现，位于TModel类的predict代码中，我发现你们好像把参考注释送到到dec中进行解码？？也就是说预测之前就已经看到了正确答案？这好像不太合理吧？是我哪里看错了理解错了，还是你们给错了代码？希望能得到你们的答疑解惑，谢谢。
![ques](https://github.com/user-attachments/assets/2e0f8653-cce3-4cdc-8b95-6a66eda52c93)

**Comment by GJCEXP** [comment]
请参考Datasetx.__getitem__中对pad_text_in的处理，训练和实际推理中的pad_text_in并不相同，训练时，pad_text_in为已有的训练数据，推理过程中pad_text_in则为[</s>,</pad>,</pad>,</pad>,…]，因此是没有问题的。

Best, 
Juncai Guo
———————————————————————————
School of Computer Science, Wuhan University

**Comment by AFunFun222** [comment]
oh!!!!原来是这样，太感谢了，谢谢你帮我解决了困扰我好几天的问题。

祝生活愉快。
