### ISSUE TITLE
max_text_len设置的问题

### ISSUE THREAD

**Issue by AFunFun222** [GJCEXP/HetCoS#2]
你好，我发现你们在java dataset上设置max_text_len的大小为38，这不太合适吧，我查了一下如果不设置这个max_text_len的大小，train_data.pkl中存在的最大长度为380诶，有45个数据的len(text)>38，你们是从什么角度出发觉得可以截断这些len>38的数据的，可以给个解释吗？

祝生活愉快

**Comment by GJCEXP** [comment]
该问题请参考README的Dataset中给的箱型图，我们是根据输入输出的数据长度分布合理设置的输出文本长度，不管在实验还是实际应用中，都不可能根据数据中最大文本长度作为输出长度，不然模型就无法实质性运行了。当然，如果你们的实验条件允许，可以把长度设置为380，性能几乎是无差别的。
